apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: mongo-demo
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:0.54.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          # env: secrets + server name
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-root-credentials
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-root-credentials
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo   # matches the mongo service name
          envFrom:
            - configMapRef:
                name: mongo-express-config
