apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: mongo-demo
spec:
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 31000   # choose in 30000-32767 range
  type: NodePort
